#cloud-config
groups:
  - docker: [root]

users:
  - name: cloud-admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker, admin
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyETMQTYrLHGzIza/aOqRvjGJ+mqSKf26gDKjCpg+OoBd5tfWQqAkCLeD1CRFyxplS9gaYiVhpffj4SdA0kus9D4Y1Zs6o+Dn6m2nAVdhjovLJfezAlaHkl5CBqM3UYqZ+SDmBV4unSE2wFpnwQPedq5+Wv915iMK6UMS/ID0tcCsqxlgcdgt2d1eipqNfDnoyfLikmoT7/0yU9TBUe5bBLRD14pukcIe2VaLldrqN0R4wN/0n0ZTF6BxhPlApYlGpOm6lb9tkOX5T5qLfRDXIHhU5/Q7yVbuo2GwYJu1DKKhWQTng/JwT9qxwryuAhfSXel0Pf8nwfGnp6IfzkXL8GhwioYaBgz8iFSpPUEgZL8NIBbv0VFj2ODV5WZmsoK1ci7yy05fHq8KdhCIOndmHvpE+1VeE+JcOn3hjF/hDhL5lnyq4iImoiefgDVxRbXpMVSiB3OvIJHyMjtW54mqPz8TwCl7G89vQk89B+mmcVfiCDNmOaFMn78YGPcsqCns=

package_update: true
package_upgrade: true

packages:
  - wget
  - unzip
  - ca-certificates
  - curl
  - gnupg

runcmd:
  # Add approximately 500 keyrings by randomly curling a bunch of files and then echo | tee'ing into random places in my filesystem because apt is trash
  - mkdir -m 0755 -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  # Install consul and nomad
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  # Do not overwrite the nomad and consul config files I've already put there
  - apt-get update && apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y consul nomad docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable consul && systemctl start consul
  - systemctl enable nomad && systemctl start nomad

write_files:
  - content: |
      datacenter = "dc1"
      data_dir   = "/opt/consul"

      server           = true
      bootstrap_expect = 1

      ui_config {
        enabled = true
      }

      client_addr = "0.0.0.0"
      bind_addr   = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/16\" | attr \"address\" }}"
      ports {
        http  = 8500
        https = -1
      }

      connect {
        enabled = true
      }

      enable_script_checks = true
    path: /etc/consul.d/consul.hcl
    permissions: '0755'


    # Nomad will try and advertise on the first private interface, which if Docker is installed will be the docker interface, so we need to explicitly set those addresses
  - content: |
      data_dir = "/opt/nomad/data"

      advertise {
        http = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/16\" | attr \"address\" }}"
        rpc = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/16\" | attr \"address\" }}"
        serf = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/16\" | attr \"address\" }}"
      }

      server {
        enabled = true
        bootstrap_expect = 1
      }
    path: /etc/nomad.d/nomad.hcl
    permissions: '0755'
