#cloud-config
groups:
  - docker: [root]

users:
  - name: cloud-admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker, admin
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyETMQTYrLHGzIza/aOqRvjGJ+mqSKf26gDKjCpg+OoBd5tfWQqAkCLeD1CRFyxplS9gaYiVhpffj4SdA0kus9D4Y1Zs6o+Dn6m2nAVdhjovLJfezAlaHkl5CBqM3UYqZ+SDmBV4unSE2wFpnwQPedq5+Wv915iMK6UMS/ID0tcCsqxlgcdgt2d1eipqNfDnoyfLikmoT7/0yU9TBUe5bBLRD14pukcIe2VaLldrqN0R4wN/0n0ZTF6BxhPlApYlGpOm6lb9tkOX5T5qLfRDXIHhU5/Q7yVbuo2GwYJu1DKKhWQTng/JwT9qxwryuAhfSXel0Pf8nwfGnp6IfzkXL8GhwioYaBgz8iFSpPUEgZL8NIBbv0VFj2ODV5WZmsoK1ci7yy05fHq8KdhCIOndmHvpE+1VeE+JcOn3hjF/hDhL5lnyq4iImoiefgDVxRbXpMVSiB3OvIJHyMjtW54mqPz8TwCl7G89vQk89B+mmcVfiCDNmOaFMn78YGPcsqCns=

package_update: true
package_upgrade: true

packages:
  - wget
  - unzip

runcmd:
  # Install consul and nomad
  - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  - apt update && apt install -y consul nomad
  - systemctl enable consul
  - systemctl start consul
  - systemctl enable nomad
  - systemctl start nomad

write_files:
  - encoding: b64
    content: |
      ewogICJkYXRhY2VudGVyIjogImRjMSIsCiAgImRhdGFfZGlyIjogIi9vcHQvY29uc3VsIiwKICAi
      bG9nX2xldmVsIjogIklORk8iLAogICJzZXJ2ZXIiOiB0cnVlLAogICJib290c3RyYXBfZXhwZWN0
      IjogMSwKICAidWkiOiB0cnVlLAogICJjbGllbnRfYWRkciI6ICJ7eyBHZXRQcml2YXRlSVAgfX0i
      LAogICJiaW5kX2FkZHIiOiAie3sgR2V0UHJpdmF0ZUlQIH19IiwKICAicG9ydHMiOiB7CiAgICAi
      aHR0cCI6IDg1MDAsCiAgICAiaHR0cHMiOiAtMQogIH0sCiAgImVuYWJsZV9zY3JpcHRfY2hlY2tz
      IjogdHJ1ZQp9Cg==
    owner: cloud-admin
    path: /etc/consul.d/server_config.json
    permissions: '0755'
  - encoding: b64
    content: |
      ewogICAgImRhdGFfZGlyIjogIi9vcHQvbm9tYWQvZGF0YSIsCiAgICAic2VydmVyIjogewogICAg
      ICAgICJlbmFibGVkIjogdHJ1ZSwKICAgICAgICAiYm9vdHN0cmFwX2V4cGVjdCI6IDEKICAgIH0K
      fQo=
    owner: cloud-admin
    path: /etc/nomad.d/server_config.json
    permissions: '0755'
